config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
=begin
get "pdr_logs/index"

get "ret_codes/edit"

get "pdrs/index"

get "ret_codes/index"

get "pdr_list/index"

get "mvno_procs/index"
=end

#get "pdrcatalog" => "mvno_procs#index"
get "mvno_procs" => "mvno_procs#index"
get "pdrs" => "pdrs#index"
get "dwh" => "dwh#index"
get "log" => "log#index"


resources :mvno_procs

resources :pdrs do
  resources :ret_codes
  get 'search', :on => :collection
  # get 'dwh', :on => :collection
end

resources :dwh do
   get 'search', :on => :collection
end


resources :log do
   get 'search', :on => :collection
end

app/models/pdr.rb
class Pdr < ActiveRecord::Base
  belongs_to :mvno_proc
  attr_accessible :notes, :mvno_proc_id, :crm_flag, :description, :dwh_flag, :from_system, :pdrstring1, :pdrstring10, :pdrstring11, :pdrstring12, :pdrstring13, :pdrstring14, :pdrstring15, :pdrstring16, :pdrstring17, :pdrstring18, :pdrstring19, :pdrstring2, :pdrstring20, :pdrstring21, :pdrstring22, :pdrstring23, :pdrstring24, :pdrstring25, :pdrstring26, :pdrstring27, :pdrstring28, :pdrstring29, :pdrstring3, :pdrstring30, :pdrstring31, :pdrstring32, :pdrstring33, :pdrstring34, :pdrstring35, :pdrstring36, :pdrstring37, :pdrstring38, :pdrstring39, :pdrstring4, :pdrstring40, :pdrstring5, :pdrstring6, :pdrstring7, :pdrstring8, :pdrstring9, :to_system
  has_many :ret_codes, :order => "code ASC"
  validates :pdrstring2, :uniqueness => {:scope => [:mvno_proc_id, :pdrstring1],  :message => "pdrkey già assegnata" }
  validate :from_to_system_check
  def get_ret_codes_list
    # returns ordered list of return codes, separated by newlines
    ret_codes_list = ''
    self.ret_codes.order("code").each {|rc| ret_codes_list << rc.code << "\n" }
    return ret_codes_list
  end

  def get_pdr_key
    # returns Pdr key concatenating process pdrtype, pdrstring1 and pdrstring2
    return  [ self.mvno_proc.pdrtype.to_s, self.pdrstring1, self.pdrstring2].join(".")
  end

private

  def from_to_system_check
    rc = true
    if (from_system != "" and to_system == "")
      errors.add(:to_system, "can't be blank if from_system is specified")
    rc = false
    end
    if (from_system == "" and to_system != "")
      errors.add(:from_system, "can't be blank if to_system is specified")
    rc = false
    end
    #if (from_system != "" and to_system != "") and (from_system == to_system)
    #  errors.add(:from_system, "and to_system can't be the same")
    #rc = false
    #end
    return rc
  end

end

app/controllers/pdrs_controller.rb
class PdrsController < ApplicationController
  unloadable
  before_filter :find_project, :authorize
  before_filter :find_pdr, :only => [:show, :edit, :update, :destroy]
  def index
    set_pdr_list("all")
  end

  def new
    @pdr = Pdr.new
  end

  def create
    @pdr = Pdr.new( params[:pdr])
    @pdr.mvno_proc = MvnoProc.find(params[:pdr][:mvno_proc_id])
    if @pdr.save
      Utils.trace_pdr("CREATE", @pdr)

      flash[:notice] = "PDR creato."
      redirect_to(@pdr)
    #    redirect_to(pdr_url(@pdr, :project_id =>  session[:project_id]))
    else
      flash[:alert] = "Errore in creazione nuovo PDR"
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @pdr.update_attributes(params[:pdr])
      Utils.trace_pdr("UPDATE", @pdr)

      flash[:notice] = "PDR aggiornato"
      redirect_to [@pdr]
    else
      flash[:alert] = "Errore in aggiornamento PDR"
      render :action => "edit"
    end
  end

  def destroy
    pdr_info = @pdr.get_pdr_key + " - " + @pdr.description
    if (@pdr.ret_codes.find_all.count == 0)
      Utils.trace_pdr("DELETE", @pdr)

      @pdr.destroy
      respond_to do |format|
        flash[:notice] = "PDR eliminato: " + pdr_info
        format.html { redirect_to(pdrs_path) }
        format.json  { head :no_content }
      end
    else
      flash[:alert] = "Impossible rimuovere il PDR: rimuovere prima tutti i codici di ritorno collegati"
      render :action => "show"
    end
  end

  def search
   logger.debug "INPUT FILTER FOR CONTROLLER  #{params[:controller]} IS #{params[:filter]}"
 
    if params[:commit] == "Reset" or params[:filter] == ""
      set_pdr_list("all")
      params[:filter] = nil
    else
      begin
        MvnoProc.find(params[:filter])  # check if input filter exists
        set_pdr_list(params[:filter])
        rescue ActiveRecord::RecordNotFound
        set_pdr_list("all")
        flash[:alert] = "Per applicare un filtro, seleziona un PdrType"
      end
    end
     render :action => "index"
  end

  private

  def find_project
    session[:project_id] ||= params[:project_id]
    @project = Project.find(session[:project_id])
  end

  def find_pdr
    @pdr = Pdr.find(params[:id])
  end

  def set_pdr_list(filter)
    if filter == "all"
      @pdr_list = Pdr.find(:all,
        :joins => :mvno_proc,
        :order => "mvno_procs.pdrtype, pdrstring1, pdrstring2" )
    else
      @pdr_list = Pdr.joins(:mvno_proc).where("mvno_procs.id = #{filter}").order("pdrstring1 ASC, pdrstring2 ASC")
    end
  end

end

app/helpers/pdrs_helper.rb
module PdrsHelper

   def get_system_options
    # return list of systems to be used in select-options html
    return [
       ["-interno-",""],
      ["AMD", "AMD"],
      ["DS","DS"],
      ["DS-LITE","DS-LITE"],
      ["GW", "GW"],
      ["KEY CLIENT", "KEY CLIENT"],
      ["PORTALE SC","PORTALE SC"],
      ["SMS", "SMS"],
      ["SSB","SSB"],
      ["TSE", "TSE"]
      ]
  end
  
 
end

app/views/pdrs/edit.html.erb
<h2>Modifica PDR</h2>

<%= render 'form' %> 


<p>
<%= link_to "Torna a elenco PDR", pdrs_path(:project_id => session[:project_id]) %>
</p>

app/views/pdrs/index.html.erb
<%= render 'shared/links' %> 

<% if (@pdr_list.count == 0) %>
  <p> Catalogo PDR vuoto! </p>
<% else %>
<%= link_to 'Crea PDR', new_pdr_path %>
<hr/>
 
 <div class = "wrapperTable">
 <div class = "wrapperHeader"> </div>
 <div class = "wrapperHeaderGold"> </div>
  <div class = "wrapperData"> 
	<table class="table" cellspacing="2">
		<thead>
 		<tr class="pdrtr">
 			<th class="pdrth" colspan="3">
 				<div class = "header"></div>
 			</th>
 			<th class="pdrth">
 				<div class = "header">Processo</div>
 			</th>
 			<th class="pdrth">
 				<div class = "header">PdrKey</div>
 			</th>
 			<th class="pdrth">
 				<div class = "header">Descrizione</div>
 			</th>
 			<th class="pdrth">
 				<div class = "header">CRM</div>
 			</th>
 			<th class="pdrth">
 				<div class = "header">DWH</div>
 			</th>
 			<th class="pdrth">
 				<div class = "header">PdrTime</div>
 </th>
 			<th class="pdrth">	<div class = "header">ServerID</div>
 </th>
 			<th class="pdrth">	<div class = "header">PdrType</div>
 </th>
 			<th class="pdrth">	<div class = "header">PdrString1</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString2</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString3</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString4</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString5</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString6</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString7</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString8</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString9</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString10</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString11</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString12</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString13</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString14</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString15</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString16</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString17</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString18</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString19</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString20</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString21</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString22</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString23</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString24</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString25</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString26</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString27</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString28</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString29</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString30</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString31</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString32</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString33</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString34</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString35</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString36</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString37</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString38</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString39</div>
  </th>
 			<th class="pdrth">	<div class = "header">PdrString40</div>
  </th>
 			</tr>
 			<tr class="pdrtr">
  			<th class="pdrth" colspan="3">
 				<div class = "header"></div>
 			</th>
				
 			<th class="pdrthgolds">	<div class = "header"> </div>
 </th>
 			<th class="pdrthgolds">	<div class = "header"> </div>
 </th>
 			<th class="pdrthgolds">	<div class = "header"> </div>
 </th>
 			<th class="pdrthgolds">	<div class = "header"> </div>
 </th>
 			<th class="pdrthgolds">	<div class = "header"> </div>
 </th>
 			<th class="pdrthgold">	<div class = "header"> - </div>
 </th>
 			<th class="pdrthgold">	<div class = "header"> - </div>
 </th>
 			<th class="pdrthgold">	<div class = "header">ProcessId</div>
 </th>
 			<th class="pdrthgold">	<div class = "header">Functional Block </div>
 </th>
 			<th class="pdrthgold">	<div class = "header">PdrID</div>
 </th>
 			<th class="pdrthgold">	<div class = "header">CustomerID</div>
  </th>
 			<th class="pdrthgold">	<div class = "header">SubsbscriberID</div>
 </th>
 			<th class="pdrthgold">	<div class = "header">MSISDN</div>
 </th>
 			<th class="pdrthgold">	<div class = "header">BusinessID</div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Business Result Code</div>
  </th>
 			<th class="pdrthgold">	<div class = "header">TSE UUID </div>
 </th>
 			<th class="pdrthgold">	<div class = "header">DS Ticket Ref</div>
 </th>
 			<th class="pdrthgold">	<div class = "header">TSE Result Code Description </div>
 </th>
 			<th class="pdrthgold">	<div class = "header">Notification Result Code </div>
 </th>
 			<th class="pdrthgold">	<div class = "header">UserID</div>
  </th>
 			<th class="pdrthgold">	<div class = "header">IP Caller </div>
 </th>
 			<th class="pdrthgold">	<div class = "header">Channel</div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
 </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 			<th class="pdrthgold">	<div class = "header">Pdr specific </div>
  </th>
 
 		</tr>	
 		</thead>
		<tbody>
  <% counter = 0
     @pdr_list.each do |pdr|
       counter += 1
   %>
    <tr class="<%= (counter % 2) == 0 ? "even" : "odd"%>">
      <td style="max-width: 20px"><%= link_to image_tag("document.png", :alt =>  "vedi dettaglio"), pdr_path(pdr) %> </td>
      <td style="max-width: 20px"><%= link_to image_tag("edit.png", :alt =>  "modifica"), edit_pdr_path(pdr) %> </td>
      <td style="max-width: 20px"><%= link_to( image_tag("delete.png", :alt =>  "rimuovi"), [pdr], :confirm => 'Sei sicuro?', :method => :delete ) %> </td>
 
      <td class="pdrtbgold"><%= pdr.mvno_proc.name %></td>
      <td class="pdrtbgold"><%= pdr.get_pdr_key %></td>
      <td class="pdrtbgold"><%= pdr.description %></td>
      <td class="pdrtbgold"><%= pdr.crm_flag=="1" ? "SI" : "NO" %> </td>
      <td class="pdrtbgold"><%= pdr.dwh_flag=="1" ? "SI" : "NO" %> </td>
      <td>PdrTime</td>
      <td>&nbsp;</td>
      <td><%= "%02d" % pdr.mvno_proc.pdrtype.to_s %></td>
      <td><%= pdr.pdrstring1 %> </td>
      <td><%= pdr.pdrstring2 %> </td>
      <td><%= pdr.pdrstring3 %> </td>
      <td><%= pdr.pdrstring4 %> </td>
      <td><%= pdr.pdrstring5 %> </td>
      <td><%= pdr.pdrstring6 %> </td>
      <td><%= simple_format(pdr.pdrstring7) %> </td>
      <td><%= pdr.pdrstring8 %> </td>
      <td><%= pdr.pdrstring9 %> </td>
      <td><%= pdr.pdrstring10 %> </td>
      <td><%= pdr.pdrstring11 %> </td>
      <td><%= pdr.pdrstring12 %> </td>
      <td><%= pdr.pdrstring13 %> </td>
      <td><%= pdr.pdrstring14 %> </td>
      <td><%= pdr.pdrstring15 %> </td>
      <td><%= pdr.pdrstring16 %> </td>
      <td><%= pdr.pdrstring17 %> </td>
      <td><%= pdr.pdrstring18 %> </td>
      <td><%= pdr.pdrstring19 %> </td>
      <td><%= pdr.pdrstring20 %> </td>
      <td><%= pdr.pdrstring21 %> </td>
      <td><%= pdr.pdrstring22 %> </td>
      <td><%= pdr.pdrstring23 %> </td>
      <td><%= pdr.pdrstring24 %> </td>
      <td><%= pdr.pdrstring25 %> </td>
      <td><%= pdr.pdrstring26 %> </td>
      <td><%= pdr.pdrstring27 %> </td>
      <td><%= pdr.pdrstring28 %> </td>
      <td><%= pdr.pdrstring29 %> </td>
      <td><%= pdr.pdrstring30 %> </td>
      <td><%= pdr.pdrstring31 %> </td>
      <td><%= pdr.pdrstring32 %> </td>
      <td><%= pdr.pdrstring33 %> </td>
      <td><%= pdr.pdrstring34 %> </td>
      <td><%= pdr.pdrstring35 %> </td>
      <td><%= pdr.pdrstring36 %> </td>
      <td><%= pdr.pdrstring37 %> </td>
      <td><%= pdr.pdrstring38 %> </td>
      <td><%= pdr.pdrstring39 %> </td>
      <td><%= pdr.pdrstring40 %> </td>
      <td style="max-width: 20px"><%= link_to image_tag("document.png", :alt =>  "vedi dettaglio"), pdr_path(pdr) %> </td>
      <td style="max-width: 20px"><%= link_to image_tag("edit.png", :alt =>  "modifica"), edit_pdr_path(pdr) %> </td>
      <td style="max-width: 20px"><%= link_to( image_tag("delete.png", :alt =>  "rimuovi"), [pdr], :confirm => 'Sei sicuro?', :method => :delete ) %> </td>
    
     </tr>
  <% end # loop on pdrs %>
	</tbody>
    </table>
  </div>
</div>
<% end %>
<hr/>
<br>
<%= link_to 'Crea PDR', new_pdr_path %>

<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'pdrcatalog', :plugin => 'pdrcatalog' %>
<% end %>

app/views/pdrs/new.html.erb
	<h2>Nuovo PDR</h2>

	<%= render 'form' %>

	<!--%= link_to "Torna a elenco PDR", pdrs_path %-->

	<%= link_to "Torna a elenco PDR", pdrs_path(:project_id =>  session[:project_id]) %>

app/views/pdrs/search.html.erb
<h1>You reached the search page</h1>
Filter is: <%= session[:filter] %>

app/views/pdrs/show.html.erb
<p>

<div id="content">

<hr />
<p>
<%= link_to( 'Modifica', edit_pdr_path(@pdr)) %> |
<%= link_to( 'Rimuovi', [@pdr], :confirm => 'Sei sicuro?', :method => :delete ) %> |
<%= link_to "Torna a Elenco PDR", pdrs_path(:project_id => session[:project_id]) %>

</p>

<h2>PDR <%= @pdr.new_record? ? "": @pdr.get_pdr_key  %></h2>


<%= form_for [@pdr] do |f| %>
<div class="box tabular">
	<div class="all_attributes">
<p><%= f.label :description %> <%= @pdr.description%></p>

<p><%= f.label :crm_flag%>     <%= @pdr.crm_flag ? "Pubblicato su CRM": "Non pubblicato su CRM"%></p>
<p><%= f.label :dwh_flag%>     <%= @pdr.dwh_flag ? "Esporta a DWH":"Non esportato a DWH"%></p>   
<p><%= f.label :from_system %> <%= @pdr.from_system %> </p>  
<p><%= f.label :to_system %>   <%= @pdr.to_system %></p>  
<p><label>PdrType</label> <%= @pdr.mvno_proc.pdrtype %></p>   
<p><%= f.label :pdrstring1 %>  <%= @pdr.pdrstring1 %></p>   
<p><%= f.label :pdrstring2 %>  <%= @pdr.pdrstring2 %></p>   
<p><%= f.label :pdrstring3 %>  <%= @pdr.pdrstring3 %></p>   
<p><%= f.label :pdrstring4 %>  <%= @pdr.pdrstring4 %></p>   
<p><%= f.label :pdrstring5 %>  <%= @pdr.pdrstring5 %></p>   
<p><%= f.label :pdrstring6 %>  <%= @pdr.pdrstring6 %></p>   
<p><%= f.label :pdrstring7 %>  <%= @pdr.pdrstring7  == '' ? "(--no ret code defined --)" : simple_format(@pdr.pdrstring7) %>
<p><label>&nbsp;</label>	<%= link_to('Dettagli/Modifica',pdr_ret_codes_path(@pdr, :project_id =>  session[:project_id])) %></p>   
<p><%= f.label :pdrstring8 %>  <%= @pdr.pdrstring8 %> </p>   
<p><%= f.label :pdrstring9 %>  <%= @pdr.pdrstring9 %> </p>   
<p><%= f.label :pdrstring10 %> <%= @pdr.pdrstring10 %></p>   
<p><%= f.label :pdrstring11 %> <%= @pdr.pdrstring11 %></p>   
<p><%= f.label :pdrstring12 %> <%= @pdr.pdrstring12 %></p>   
<p><%= f.label :pdrstring13 %> <%= @pdr.pdrstring13 %></p>   
<p><%= f.label :pdrstring14 %> <%= @pdr.pdrstring14 %></p>   
<p><%= f.label :pdrstring15 %> <%= @pdr.pdrstring15 %></p>   
<p><%= f.label :pdrstring16 %> <%= @pdr.pdrstring16 %></p>   
<p><%= f.label :pdrstring17 %> <%= @pdr.pdrstring17 %></p>   
<p><%= f.label :pdrstring18 %> <%= @pdr.pdrstring18 %></p>   
<p><%= f.label :pdrstring19 %> <%= @pdr.pdrstring19 %></p>   
<p><%= f.label :pdrstring20 %> <%= @pdr.pdrstring20 %></p>   
<p><%= f.label :pdrstring21 %> <%= @pdr.pdrstring21 %></p>   
<p><%= f.label :pdrstring22 %> <%= @pdr.pdrstring22 %></p>   
<p><%= f.label :pdrstring23 %> <%= @pdr.pdrstring23 %></p>   
<p><%= f.label :pdrstring24 %> <%= @pdr.pdrstring24 %></p>   
<p><%= f.label :pdrstring25 %> <%= @pdr.pdrstring25 %></p>   
<p><%= f.label :pdrstring26 %> <%= @pdr.pdrstring26 %></p>   
<p><%= f.label :pdrstring27 %> <%= @pdr.pdrstring27 %></p>   
<p><%= f.label :pdrstring28 %> <%= @pdr.pdrstring28 %></p>   
<p><%= f.label :pdrstring29 %> <%= @pdr.pdrstring29 %></p>   
<p><%= f.label :pdrstring30 %> <%= @pdr.pdrstring30 %></p>   
<p><%= f.label :pdrstring31 %> <%= @pdr.pdrstring31 %></p>   
<p><%= f.label :pdrstring32 %> <%= @pdr.pdrstring32 %></p>   
<p><%= f.label :pdrstring33 %> <%= @pdr.pdrstring33 %></p>   
<p><%= f.label :pdrstring34 %> <%= @pdr.pdrstring34 %></p>   
<p><%= f.label :pdrstring35 %> <%= @pdr.pdrstring35 %></p>   
<p><%= f.label :pdrstring36 %> <%= @pdr.pdrstring36 %></p>   
<p><%= f.label :pdrstring37 %> <%= @pdr.pdrstring37 %></p>   
<p><%= f.label :pdrstring38 %> <%= @pdr.pdrstring38 %></p>   
<p><%= f.label :pdrstring39 %> <%= @pdr.pdrstring39 %></p>   
<p><%= f.label :pdrstring40 %> <%= @pdr.pdrstring40 %></p>   
<p><%= f.label :notes %> <%= @pdr.notes %></p>   

  </div>
</div>
<% end %>

<p>
<%= link_to "Modifica", edit_pdr_path(@pdr) %>
<%= link_to( 'Rimuovi', [@pdr], :confirm => 'Sei sicuro?', :method => :delete ) %>
</p>


<hr/>
<p>
<%= link_to "Torna a Elenco PDR", pdrs_path(:project_id => session[:project_id]) %>
</p>

</div>