config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
=begin
get "pdr_logs/index"

get "ret_codes/edit"

get "pdrs/index"

get "ret_codes/index"

get "pdr_list/index"

get "mvno_procs/index"
=end

#get "pdrcatalog" => "mvno_procs#index"
get "mvno_procs" => "mvno_procs#index"
get "pdrs" => "pdrs#index"
get "dwh" => "dwh#index"
get "log" => "log#index"


resources :mvno_procs

resources :pdrs do
  resources :ret_codes
  get 'search', :on => :collection
  # get 'dwh', :on => :collection
end

resources :dwh do
   get 'search', :on => :collection
end


resources :log do
   get 'search', :on => :collection
end

app/models/mvno_proc.rb
class MvnoProc < ActiveRecord::Base
  validates :pdrtype, :presence => true, :numericality => { :greater_than => -1 }, :uniqueness => true
  validates :name, :presence => true
  attr_accessible :name, :pdrtype
  has_many :pdrs
  
  
  def option_text
    return "%02d" % pdrtype.to_s + " - " + name
  end
end

app/controllers/mvno_procs_controller.rb
class MvnoProcsController < ApplicationController
  unloadable
  before_filter :find_project, :authorize

  def index

    @project = Project.find(params[:project_id])
    @mvno_proc_list = MvnoProc.order("pdrtype")
  end

  def new
    @mvno_proc = MvnoProc.new
  end

  def create
    @mvno_proc = MvnoProc.new(params[:mvno_proc])
    if @mvno_proc.save
      flash[:notice] = "Il processo e' stato creato."
      redirect_to(mvno_procs_url(:project_id =>  session[:project_id]))
    else
      flash[:alert] = "Il processo non e' stato creato"
      render :action => "new"
    end
  end

  def show
    @mvno_proc = MvnoProc.find(params[:id])
  end

  def edit
    @mvno_proc = MvnoProc.find(params[:id])
  end

  def update
    @mvno_proc = MvnoProc.find(params[:id])
    respond_to do |format|
      if @mvno_proc.update_attributes(params[:mvno_proc])
        flash[:notice] = "Aggiornamento eseguito."
        format.html {  redirect_to(mvno_procs_url(:project_id =>  session[:project_id])) }
        format.json  { head :no_content }
      else
      #flash[:alert] = "Errore in aggiornamento."
        format.html { render :action => "edit" }
        format.json  { render :json => @mvno_proc.errors,
        :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @mvno_proc = MvnoProc.find(params[:id])
    pdrtype = @mvno_proc.pdrtype
    name = @mvno_proc.name
    if @mvno_proc.pdrs.find_all.count == 0
      @mvno_proc.destroy
      respond_to do |format|
        flash[:notice] = "Il Processo '#{pdrtype}- #{name}' e' stato rimosso!"
        format.html { redirect_to(mvno_procs_url(:project_id =>  session[:project_id]) ) }
        format.json  { head :no_content }
      end
    else
      flash[:alert] = "Impossible rimuovere il processo: rimuovere prima i PDR collegati"
      render :action => "show"

    end
  end

  private

  def find_project
    session[:project_id] ||= params[:project_id]
    @project = Project.find(session[:project_id])
  end

end

app/helpers/mvno_procs_helper.rb
module MvnoProcsHelper
 
end

app/views/mvno_procs/_form.html.erb
<%= form_for(@mvno_proc) do |f| %>
<div class="box tabular">
	<div class="all_attributes">
  <% if @mvno_proc.errors.any? %>
      <div id="alert">
        <h2><%= pluralize(@mvno_proc.errors.count, "error") %>
            prohibited this mvno_proc from being saved:</h2>
      <ul>
      <% @mvno_proc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p> 
    <%= f.label :pdrtype %><%= f.text_field :pdrtype %>
</p>
<p> 
    <%= f.label :name %><%= f.text_field :name %>
</p>


<p> 
    <%= f.submit (@mvno_proc.new_record? ? 'Crea Processo' : 'Salva Modifiche')%>
</p>

  </div>  
</div>  

<% end %>

app/views/mvno_procs/edit.html.erb
<h2>Modifica Processo</h2>

<%= render 'form' %> 

<%= link_to 'Torna all\'elenco', mvno_procs_path(:project_id =>  session[:project_id]) %>

app/views/mvno_procs/index.html.erb
<%= render 'shared/links' %> 

<% if (@mvno_proc_list.size == 0) %>
  <p>   Elenco Processi vuoto! </p>

<% else %>

<p> <%= link_to "Crea Nuovo Processo", new_mvno_proc_path %> </p>
<hr/>
<table class="list" style="width:auto">
	<tr>
	<th>PdrType</th>
	<th>Nome Processo</th>
	<th>Num.Pdr</th>
	<th colspan="2">&nbsp;</th>
	</tr>

<% counter = 0
   @mvno_proc_list.each do |mvno_proc| 
   counter += 1
%>
	<tr class="<%= (counter % 2) == 0 ? "even" : "odd"%>">
	<td><%= mvno_proc.pdrtype %></td>
	<td><%= mvno_proc.name %></td>
	<td align="right"><%= mvno_proc.pdrs.count %></td>
	<td><%= link_to 'Modifica', edit_mvno_proc_path(mvno_proc) %></td>
	<td><%= link_to 'Rimuovi', mvno_proc, :confirm => 'Sei sicuro?',
	:method => :delete %></td>
	</tr>
	<% end %>
</table>
<% end %>

<hr/>
<p> <%= link_to "Crea Nuovo Processo", new_mvno_proc_path %> </p>

app/views/mvno_procs/new.html.erb
<h2>Nuovo Processo</h2>

<%= render 'form' %> 

<%= link_to 'Torna all\'elenco', mvno_procs_path(:project_id =>  session[:project_id]) %>

app/views/mvno_procs/show.html.erb
<div>
<h2>
Processo:<%= @mvno_proc.pdrtype %>&nbsp; <%= @mvno_proc.name %>
</h2>
</div>

<div>
   <%= link_to 'Torna all\'elenco Processi', mvno_procs_path(:project_id => session[:project_id]) %> |
   <%= link_to 'Modifica', edit_mvno_proc_path(@mvno_proc) %> |
<%= link_to 'Rimuovi', @mvno_proc, :confirm => 'Sei sicuro?',
:method => :delete %>
</div>

<hr/>


<% if  @mvno_proc.pdrs.find_all.count == 0 %>
<h3> Nessun PDR definito </h3>
<% else %>
<h3> Elenco PDR</h3>

 <table class="pdrtable">
    <tr class="pdrth">
      <th>Ultima modifica</th>
      <th>Nome Proc</th>
      <th>PdrKey</th>
      <th>Descrizione</th>
    </tr>

<% counter = 0
   @mvno_proc.pdrs.find_all do |pdr| 
     counter += 1 
%>
    <tr class="<%= (counter % 2) == 0 ? "even" : "odd" %> ">
      <td><%= pdr.updated_at.to_formatted_s(:db) %> </td>
      <td><%= pdr.mvno_proc.name %></td>
      <td><%= pdr.get_pdr_key %></td>
      <td><%= pdr.description%></td>      
    </tr>
  <% end # pdr loop%>
</table>
<% end # if-then-else%>