config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
=begin
get "pdr_logs/index"

get "ret_codes/edit"

get "pdrs/index"

get "ret_codes/index"

get "pdr_list/index"

get "mvno_procs/index"
=end

#get "pdrcatalog" => "mvno_procs#index"
get "mvno_procs" => "mvno_procs#index"
get "pdrs" => "pdrs#index"
get "dwh" => "dwh#index"
get "log" => "log#index"


resources :mvno_procs

resources :pdrs do
  resources :ret_codes
  get 'search', :on => :collection
  # get 'dwh', :on => :collection
end

resources :dwh do
   get 'search', :on => :collection
end


resources :log do
   get 'search', :on => :collection
end

app/models/ret_code.rb
class RetCode < ActiveRecord::Base
  belongs_to :pdr
  attr_accessible :cm_description, :code, :comment, :crm_fields, :description
    
  def self.get_ret_codes_options
   # returns as list of options (array of 2-uples) all error codes defined in the db
   return RetCode.select(:code).uniq.order(:code).map {|rc| [rc.code,rc.code]}
  end
end

app/controllers/ret_codes_controller.rb
class RetCodesController < ApplicationController
  unloadable
  before_filter :find_project, :authorize
  before_filter :find_pdr
  before_filter :find_ret_code, :only => [:show, :edit, :update, :destroy]
  def index
    @ret_code = @pdr.ret_codes.build
  end

  def new
    @ret_code = RetCode.new
  end

  def create

    @ret_code = @pdr.ret_codes.build(params[:ret_code])
    @ret_code.code = params[:ret_code][:code] !='' ? params[:ret_code][:code] :  params[:code_sel]
    if @ret_code.save
      Utils.trace_pdr("NEW RET_CODE", @pdr)  # trace pdr in log table
      # copying new code in corresponding pdr, field pdrstring7
      @pdr.pdrstring7 = @pdr.get_ret_codes_list
      @pdr.save
      flash[:notice] = "Nuovo Return Code creato!"

      redirect_to pdr_ret_codes_url(@pdr)
    #   redirect_to [@mvno_proc, @pdr]
    else
      flash[:alert] = "Errore in creazione nuovo Return Code"
      render :action => "new"
    end
  end

  def edit

  end

  def update
    # handle precedence between select and text fields
    form_params = params[:ret_code]
    form_params[:code] = params[:ret_code][:code ]!='' ? params[:ret_code][:code] :  params[:code_sel]
    if @ret_code.update_attributes(form_params)
      Utils.trace_pdr("UPDATE RET_CODE", @pdr)  # trace pdr in log table
      # copying new code in corresponding pdr, field pdrstring7
      @pdr.pdrstring7 = @pdr.get_ret_codes_list
      @pdr.save

      flash[:notice] = "Return Code  aggiornato"
      redirect_to( pdr_ret_codes_url(@pdr))
    else
      flash[:alert] = "Errore in aggiornamento Return Code"
      render :action => "edit"
    end
  end

  def destroy
    @ret_code.destroy
    Utils.trace_pdr("DELETE", @pdr)
     # copying new code in corresponding pdr, field pdrstring7
      @pdr.pdrstring7 = @pdr.get_ret_codes_list
      @pdr.save    
#    respond_to do |format|
      flash[:notice] = "Codice di ritorno eliminato"
      #redirect_to( pdr_ret_codes_url(@pdr, :project_id =>  session[:project_id]))
      redirect_to( pdr_ret_codes_url(@pdr))
 #   end
  end

private

  def find_project
    session[:project_id] ||= params[:project_id]
    @project = Project.find(session[:project_id])
  end

  def find_pdr
    @pdr = Pdr.find(params[:pdr_id])
  end

  def find_ret_code
    @ret_code = @pdr.ret_codes.find(params[:id])
  end

end

app/helpers/ret_codes_helper.rb
module RetCodesHelper
end

app/views/ret_codes/_form.html.erb
<%= form_for [@pdr, @ret_code] do |f| %>
<div class="box tabular">
	<div class="all_attributes">
  <% if @ret_code.errors.any? %>
      <div id="alert">
        <h2><%= pluralize(@ret_code.errors.count, "error") %>
            prohibited this ireturn code from being saved:</h2>
      <ul>
      <% @ret_code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p>
   <label>Codice Errore:</label>
</p>	  
    <% if RetCode.get_ret_codes_options.count > 0 %> 
      <p>
          <label>seleziona un valore</label> 
          <%= select_tag(:code_sel, options_for_select(RetCode.get_ret_codes_options ,nil), :onchange => raw("document.getElementById('ret_code_code').value=this.options[this.selectedIndex].value")) %>
          o, in alternativa,
      </p>
    <% end %>
<p>
	<label>inserisci un nuovo valore</label> <%= f.text_field :code %>
</p>	  
<p>
    <%= f.label :description %>  <%= f.text_area :description %>
</p>	  
<p>
    <%= f.label :cm_description %> <%= f.text_field :cm_description %>
</p>	  
<p>
    <%= f.label :crm_fields %>  <%= f.text_field :crm_fields %>
</p>	  
<p>
    <%= f.label :comment %> <%= f.text_field :comment %>
</p>	  
 
<p>
    <%= f.submit (@ret_code.new_record? ? 'Crea' : 'Salva')%>
</p>

  </div>
</div>
<% end %>

app/views/ret_codes/edit.html.erb
<h2>Modifica Return Codes</h2>

<%= render 'form' %> 

<%= link_to "Torna a elenco Codici PDR", pdr_ret_codes_path(@pdr)  %>

app/views/ret_codes/index.html.erb
<h3>Codici di Ritorno PDR: <%= @pdr.get_pdr_key %></h3>

<% if  @pdr.ret_codes(true).size == 0 %>
<h4> Nessun Codice di Ritorno definito</h4>
<% else %>
<table class="list" style="width:auto; border-collapse: separate; border-spacing:2px; border-color:grey;" >
	<tr class="pdrth">
		<th colspan="2">&nbsp;</th>
		<th>Codice Errore</th>
		<th>Descrizione</th>
		<th>Descrizione CM</th>
		<th>Campi aggiuntivi da visualizzare su CRM</th>
		<th>Commento</th>
		<th colspan="2">&nbsp;</th>
	</tr>
	<% counter = 0
	@pdr.ret_codes.find_all do |rc|
	counter +=1
	%>
	<tr class="<%= (counter % 2) == 0 ? "even" : "odd"%>">
		<td><%= link_to( image_tag("edit.png", :alt =>  "modifica"), edit_pdr_ret_code_path(@pdr, rc)) %> </td>
		<td><%= link_to( image_tag("delete.png", :alt =>  "rimuovi"), [@pdr, rc], :confirm => 'Sei sicuro?', :method => :delete ) %></td>
		<td><%= rc.code %></td>
		<td><%= simple_format(rc.description) %></td>
		<td><%= rc.cm_description %></td>
		<td><%= rc.crm_fields %></td>
		<td><%= rc.comment %></td>
		<td><%= link_to( image_tag("edit.png", :alt =>  "modifica"), edit_pdr_ret_code_path(@pdr, rc)) %> </td>
		<td><%= link_to( image_tag("delete.png", :alt =>  "rimuovi"), [@pdr, rc], :confirm => 'Sei sicuro?', :method => :delete ) %></td>
	</tr>
	<% end # loop %>
</table>

<% end %>

<p>
	<%= link_to( 'Aggiungi Codice di Ritorno', new_pdr_ret_code_path(@pdr))  %>
</p>

<br>
<hr/>
<%= link_to( 'Torna al PDR', pdr_path(@pdr) )%>

app/views/ret_codes/new.html.erb
<h2>PDR <%= @pdr.get_pdr_key %></h2>
<h2>Nuovo Codice di Ritorno</h2>

<%= render 'form' %> 

<%= link_to "Torna a elenco Codici PDR", pdr_ret_codes_path(@pdr)  %>